name: Build APK Android

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show structure
        run: find . -maxdepth 4 -type f | grep -v ".git" | head -60

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x android_apk/gradlew

      - name: Build APK Debug
        run: cd android_apk && bash gradlew assembleDebug --no-daemon --stacktrace

      - name: Find APK
        run: find . -name "*.apk" -type f

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: UPN-Presence-APK
          path: android_apk/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
